Build Test:
  stage: deploy
  when: manual
  only:
    refs:
      - master
  script:
    - tar -Jxf node-linux.tar.xz
    - export PATH=$PATH:$(pwd)/node-v14.16.0-linux-x64/bin
    - npm install --production
    - npm run-script build


Deploy to Testing:
  stage: deploy
  when: manual
  only:
    refs:
      - master
  script:
    - rm node-linux.tar.xz
    - mv package-prod-test.json package.json
    - /usr/local/bin/eb-deploy.sh "Ins Follower" www-easygetinsta-com2-test liSsLweGBAmc487bBDoJvwiEmrMd44fG



Deploy to Production:
  stage: deploy
  when: manual
  only:
    refs:
      - master
  script:
    - rm node-linux.tar.xz
    - /usr/local/bin/eb-deploy.sh "Ins Follower" www-easygetinsta-com2 liSsLweGBAmc487bBDoJvwiEmrMd44fG
